### ISSUE TITLE
gitlabbot issue recognizing subgroups

### ISSUE THREAD

**Issue by robrigo** [keybase/managed-bots#111]
In Gitlab, you can organize repositories within a group by creating subgroups. The bot doesn't yet allow for this on projects with a URL such as https://gitlab.com/eos-detroit/tech-ops/eosio-bp-playbooks, as it only expects <owner/repo>

**Comment by Daniel-Wang** [comment]
@robrigo thanks for the input!
Will take a look to add in the option for <owner/subgroup/.../repo>

**Comment by joshblum** [comment]
@robrigo the new bot version is live, let me know if you have any issues

**Comment by robrigo** [comment]
Works well now. thanks!

**Comment by AmandaCameron** [comment]
This seems to have been broken again by the self-hosted PR, unless I'm reading the master source wrong.

**Comment by joshblum** [comment]
@AmandaCameron thanks, we'll put a fix out. cc @Daniel-Wang

**Comment by joshblum** [comment]
closed via https://github.com/keybase/managed-bots/pull/157
