### ISSUE TITLE
Issue with webhookbot and Radarr

### ISSUE THREAD

**Issue by Backspaze** [keybase/managed-bots#112]
The webhookbot doesn't seem fully compatible with [Radarr](https://github.com/Radarr/Radarr) or I'm doing something wrong.

I added the webhook to Radarr as in the screenshot below. But the only thing that gets posted in the Keybase chat is **[hook: radarr]** (radarr is the name of the webhook) no matter if I just click the **Test** button in  Radarr or if it's a real grab/download message. It doesn't matter weather I choose **POST** or **PUT** as method.

More info about webhooks in Radarr can be found [here](https://github.com/Radarr/Radarr/wiki/Webhook)

![bild](https://user-images.githubusercontent.com/12255362/73598043-6518e380-4533-11ea-8c63-f10b8f1b5299.png)

**Comment by joshblum** [comment]
@Backspaze, just deployed a fix. Please let me know if you have any otherissues, thanks for reporting!

**Comment by Backspaze** [comment]
I'm certainly getting the whole message now, but it seems to be pure JSON format or something like that, so it's not very pretty.

```json
[hook: radarr]

{
  "remoteMovie": {
    "tmdbId": 1234,
    "imdbId": "5678",
    "title": "Test title",
    "year": 1970
  },
  "release": {
    "quality": "Test Quality",
    "qualityVersion": 1,
    "releaseGroup": "Test Group",
    "releaseTitle": "Test Title",
    "indexer": "Test Indexer",
    "size": 9999999
  },
  "eventType": "Test",
  "movie": {
    "id": 1,
    "title": "Test Title",
    "releaseDate": "1970-01-01",
    "folderPath": "C:\testpath"
  }
}
```
As a comparison I remember using this in Telegram which resulted in a nicely formatted message with a IMDb link, similar to how the email alternative looks like, example below.

Subject: **Radarr [Movie] - Downloaded**
Body: **Movie title (1970) [Bluray-1080p] https://www.imdb.com/title/tt123456789/ Downloaded and sorted.**

**Comment by joshblum** [comment]
We are working on generic formatting, I can let you know when it’s
implemented. What telegram app did you use?

**Comment by Backspaze** [comment]
@joshblum 
Great. I assume all of these managed bots get updated automatically so I'll know when it's implemented when the notification changes format from JSON to generic?

I used the official Telegram app on Windows and iOS.
