### ISSUE TITLE
GitLab bot - no notifications

### ISSUE THREAD

**Issue by Backspaze** [keybase/managed-bots#120]
I used !gitlabbot feedback to report an issue about not getting any notifications and got some basic troubleshooting tips from @Daniel-Wang but that didn't solve the issue, so I'll submit this as an issue here instead.

Copy/paste of my initial feedback but formatted for easier reading:
> I'm not getting any notifications.
> - Does it matter if the project is private or public?
> - Does it matter if the owner/username contains capital letters?
>   - My username begins with a capital letter and the URL in the browser reflects that, but in Keybase the URL is shown in all lower case. Clicking the link in Keybase that leads to the webhook settings in GitLab sends me to the correct site, but I can see the URL change in the browser from lower to uppercase for my username.

I've made sure that the webhook url is correct, and I've ticked all the types of events.

When saving the webhook configuration in GitLab there was a "success" message and using the test funtion gave no errors, and running a real push and pipeline job all seems to run just fine, I just don't get any notifications in keybase.

Below is a screenshot of the log in in "Recent Deliveries" for the webhook in GitLab.
![bild](https://user-images.githubusercontent.com/12255362/73781239-2d5aa780-4790-11ea-852e-b34d884aca62.png)

**Comment by joshblum** [comment]
@Backspaze can you DM me on keybase to discuss further? I'm `@joshblum` there too, https://keybase.io/joshblum/

**Comment by Backspaze** [comment]
DM sent.

**Comment by steffo** [comment]
same issue here. Like to share how this is resolved?

**Comment by Backspaze** [comment]
@steffo copy/paste from chat:

> but we dn't support a default branch that isn't called `master` at the moment, we will think about a fix

> you can do `!gitlab subscribe <repo> <branch>`

**Comment by joshblum** [comment]
@steffo default non-master branches are no supported. You can DM me with more details on your setup
