### ISSUE TITLE
githubbot: Closing of issue is attributed to the wrong person

### ISSUE THREAD

**Issue by Hexstream** [keybase/managed-bots#139]
I pushed [this commit](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/commit/ae1f0b0a13b2df9c0eeb935ed4cfefa22a0fef7e) which closed [this issue](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/15) but the bot announced the following:

```
awolven closed issue #15 on common-lispers.hexstreamsoft.com.
https://github.com/Hexstream/common-lispers.hexstreamsoft.com/issues/15
```

awolven (the issue creator) did not close the issue, I did.

I'm not sure if this bug only occurs when closing via commit or always.

**Comment by hyperobject** [comment]
Thanks for the report! I'll take a look.

**Comment by hyperobject** [comment]
@Hexstream should be fixed in prod once we deploy later!
