### ISSUE TITLE
githubbot/gitlabbot: list

### ISSUE THREAD

**Issue by svoop** [keybase/managed-bots#140]
Not sure whether this is really needed, maybe in the interest of housekeeping: After subscribing numerous repos, I'm certain not to remember which ones in a few weeks time. How about adding

```
!github list
!gitlab list
```

to get a list of all subscriptions and therefore the ability to unsubscribe from no longer needed or incorrect subscriptions (typos etc)?

**Comment by Hexstream** [comment]
Agreed, but try `!github subscribe --list`.

**Comment by joshblum** [comment]
We can add the `--list` functionality to gitlabbot as well

**Comment by svoop** [comment]
Thanks for the hint, I haven't seen that argument on the githubbot. Any particular reason why these bots work with arguments and the webhookbot implements a separate command? Since all three are managed, consistency might be a point as well.

**Comment by Hexstream** [comment]
By the way I found that (undocumented?) feature during autocomplete.
