### ISSUE TITLE
githubbot: Bot became irresponsive regarding active subscriptions and commands

### ISSUE THREAD

**Issue by Hexstream** [keybase/managed-bots#143]
I made no changes to my subscriptions and pushed [3 new commits](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/commits/master) after [this commit](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/commit/9f514d3c4d80eb1c704a7bec1e666883d2d7980f) yet I did not receive the expected messages.

I also tried `!github subscribe --list` and `!github subscribe` and `!github subscribe foo` with no response from the bot.

**Comment by hyperobject** [comment]
@Hexstream Can you DM me on keybase to discuss further? I'm `@01` on there, https://keybase.io/01. Thanks!

**Comment by Hexstream** [comment]
Will do!

**Comment by hyperobject** [comment]
Closing since this is an exploding messages issue and out of scope for this repo.

**Comment by Hexstream** [comment]
This issue still persists, and I believe it would be far more useful to let this issue live here rather than adding it to the already catastrophically overloaded [keybase-issues repo](https://github.com/keybase/keybase-issues/issues) which has a whopping 2080 open issues, or, worse yet, not formally tracking this anywhere.

**Comment by joshblum** [comment]
This is being tracked internally and will be worked on soon. In the interim
you can use non-exploding messages with the bot.

**Comment by Hexstream** [comment]
I'm happy to report that I successfully received a notification today!

**Comment by Hexstream** [comment]
Unfortunately this issue has resurfaced. I [pushed some new commits](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/commits/master) since March 1 and the bot did not send the expected notifications.

**Comment by joshblum** [comment]
The fix is the latest client version which is going to be released shortly.

**Comment by Hexstream** [comment]
Perfect! Thank you.
