### ISSUE TITLE
Google Meet Bot compatability with hangouts video invite links

### ISSUE THREAD

**Issue by tourBermuda** [keybase/managed-bots#201]
Would it be possible to allow the Google Meet bot, to also generate links to Google hangouts video chat?  I think it  may use a lot of the same google services? Also since Google meet is restricted to Gsuite users (a paid service), so it limits the use. My knowledge of this  is limited at best, it just a suggestion.

**Comment by joshblum** [comment]
@tourBermuda hangout links are generated for non gsuite accounts. Are you hitting any specific error?

**Comment by tourBermuda** [comment]
@joshblum  Ok, sorry I have not actually tried it yet. However I was looking at the managed bot blog announcement as well as github code. I did not see anything about hangouts. So I just thought I would ask. Thanks I"ll give it a try.
