### ISSUE TITLE
jira-bot: No response from host

### ISSUE THREAD

**Issue by C0DK** [keybase/managed-bots#220]
![image](https://user-images.githubusercontent.com/9048078/79110027-d964d400-7d79-11ea-822b-dee8330d1035.png)
I get the above error on jira - Jira is using their cloud option.

**Comment by songgao** [comment]
That's OK -- just hit continue and configure "Incoming Authentication" by clicking the 🖋icon.

**Comment by C0DK** [comment]
Thank you - i got it working, but as stated in the other issue, i think the message could be more clear. I'll love to make a PR that makes the message just a bit more clear.

**Comment by songgao** [comment]
Great! Thanks @C0DK . I'm gonna close this one and we can track the issue of unclear message in https://github.com/keybase/managed-bots/issues/221 .
