### ISSUE TITLE
webhookbot - image urls don't preview

### ISSUE THREAD

**Issue by bettse** [keybase/managed-bots#265]
I have webhookbot installed in a chat channel and posting links to images, but they don't show a preview in my MacOS desktop client.  If I copy the link and paste it as a message from me, it does.  Is this a missing feature of the bot, or a limitation based on it's access?

**Comment by joshblum** [comment]
The bot opts out of unfurling links

**Comment by bettse** [comment]
Is it explicitly opting out, or does the code not support the unfurl?  I'm asking because I wonder if it can be made an option, or if I can enable it if I run the bot myself, or if it is a missing feature that I would have to add code to support.

**Comment by joshblum** [comment]
The bot just opts out, if you run the bot yourself you can enable link
previews under Settings > Chat > Link Previews

**Comment by bettse** [comment]
Ah, and since it is global, that is why (I'm guessing) it can't be configured
Thanks!
