### ISSUE TITLE
"Something went wrong!" when trying to subscribe or unsubscribe to repo events

### ISSUE THREAD

**Issue by knorrium** [keybase/managed-bots#272]
After setting up the Keybase integration on a repository, I can't subscribe or unsubscribe to any event types. githubbot always responds with `Something went wrong!`. 

I couldn't setup my own instance to debug further, but it seems to be thrown by line 219 here

https://github.com/keybase/managed-bots/blob/66508ee4420b0550ece29981a2fac68ae7ce316a/githubbot/githubbot/db.go#L205-L221

**Comment by joshblum** [comment]
@knorrium, thanks for the report this is fixed in https://github.com/keybase/managed-bots/commit/bda636ad470f8c588febe8862eee64ac7e01bf33. deploying an updated bot now

**Comment by knorrium** [comment]
@joshblum thanks for the fix - that was easy to miss :) can you confirm if the update has been deployed? I'm still seeing the error after removing the app and revoking access. I can't even subscribe to the repo updates for the first time after setting up the integration now.

**Comment by joshblum** [comment]
@knorrium there was an additional query error, should be fixed now

**Comment by knorrium** [comment]
@joshblum it looks like there's still something left to be fixed. was the new column added to the table or perhaps the db migration wasn't done? new subscriptions don't seem to be working
