### ISSUE TITLE
Keybase webhookbot not responding

### ISSUE THREAD

**Issue by fleish** [keybase/managed-bots#303]
Webhookbot on keybase is not responding to commands & attempts to POST to existing URLs are receiving 504 Gateway Timeout errors.

**Comment by joshblum** [comment]
@fleish I restarted the bot and it's responding to messages from me, can you confirm?

**Comment by joshblum** [comment]
@fleish I put some rate limiting in, https://github.com/keybase/managed-bots/pull/304, bot seems more stable.

**Comment by fleish** [comment]
@joshblum is that live now? I'm still getting 504 gateway timeouts and no responses from the bot directly

**Comment by fleish** [comment]
@joshblum I started getting some responses back now, but with significant delays. My direct message sent via keybase @ 1253 was replied to @ 1319. Similar behavior for the webhook I posted @ about the same time and got a 504 timeout response - I see the message was posted to keybase ~25 minutes later.

**Comment by fleish** [comment]
@joshblum final update for now. I also have a daily script that tries to post a webhook via the bot that got a 504 timeout @ Date: Tue, 13 Dec 2022 19:01:01 +0000, but that one never showed up on keybase today

**Comment by joshblum** [comment]
@fleish thanks for investigating. I additionally beefed up that bot machine, it was pushing it's limits.

**Comment by fleish** [comment]
@joshblum thanks for fixing, as of now I am not getting 504 timeouts and response time for web hook posts & direct messages are back to normal

**Comment by fleish** [comment]
reopening as things appear to have regressed

**Comment by joshblum** [comment]
https://github.com/keybase/go-keybase-chat-bot/pull/84 is a potential fix here. If the chat server is slow to process a request, any subsequent chat sends (hook processing) would be blocked behind it
